### ISSUE TITLE
variational_quantum_eigensolver -1 or +1 coefficient 

### ISSUE THREAD

**Issue by elizalexander** [DavitKhach/quantum-algorithms-tutorials#3]
At the end of variational_quantum_eigensolver.ipynb, you explain the following:
![image](https://user-images.githubusercontent.com/47868036/85076908-f94bb600-b175-11ea-93bf-2788581137e5.png)

In that last line, do you mean with -1 coefficient for those eigenvectors which eigenvalue is -1 and with +1 coefficient for those eigenvectors which eigenvalue is **+1**?

**Comment by DavitKhach** [comment]
Yes, indeed there should be **+1** at the end of the last line. Thank you for mentioning it here.
